name: deploy

on:
    push:
        branches:
        - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Set up SSH
              run: |
                mkdir -p ~/.ssh/
                echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa

            - name: Sett up known hosts
              run: |
                echo "${{ secrets.SSH_KNOWN_HOSTS}}" >> ~/.ssh/known_hosts
                chmod 644 ~/.ssh/known_hosts

            - name: Check Node.js and TypeScript version
              run: |
                node --version
                npx tsc --version

            - name: SSH and deploy
              run: |
                ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_PUBLIC_IP }} "
                  cd express || exit 1
                  git pull || exit 2
                  npm install || exit 3
                  npm run build || exit 4
                  sudo pkill node || exit 5
                  nohup sudo npm start > /dev/null 2>&1 &
                  npx wait-on http://localhost -t 30000
                  exit
                "
